export const videoUrls: Record<string, string> = {
  EINBEINSTAND_LEVEL_1_BALL_HALTEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086742/claudia-clips/vevdji7xiznq1ttxrrlc.mp4",
  EINBEINSTAND_LEVEL_2_BALL_MIT_PARTNER_WERFEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086745/claudia-clips/bvx3qztlgwebxcv0sez6.mp4",
  EINBEINSTAND_LEVEL_3_PARTNER_TESTEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086748/claudia-clips/becfyzchkam6exqx4oth.mp4",
  KNIEBEUGEN_LEVEL_1_MIT_ZEHENHEBEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086751/claudia-clips/snveganqjzbuqlcqp001.mp4",
  KNIEBEUGEN_LEVEL_2_AUSFALLSCHRITTE_IM_GEHEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086754/claudia-clips/mauimmbqdgnhjtkvogck.mp4",
  KNIEBEUGEN_LEVEL_3_EINBEINIGE_KNIEBEUGEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086759/claudia-clips/psnnakbv5ripm4oa4yas.mp4",
  KOPENHAGEN_ADDUKTOREN_UEBUNG_LEVEL_1_SEITLICHES_BEINHEBEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086762/claudia-clips/xg42dv2foxr9wkqu19rk.mp4",
  KOPENHAGEN_ADDUKTOREN_UEBUNG_LEVEL_2_OBERES_KNIE_GESTUETZT:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086765/claudia-clips/rnzt4iqtt2qr1qjgmy7r.mp4",
  KOPENHAGEN_ADDUKTOREN_UEBUNG_LEVEL_3_OBERER_KNOECHEL_GESTUETZT:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086767/claudia-clips/hwnzo8ogenafh9p0qald.mp4",
  LAUFEN_GERADEAUS:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086770/claudia-clips/vec8kmrfsguldnma6nsn.mp4",
  LAUFEN_HOCH_WEIT_SPRUENGE:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086776/claudia-clips/un1e8ta9vojd2zvqozou.mp4",
  LAUFEN_HUEFTDREHUNG_NACH_AUSSEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086781/claudia-clips/yfozuptgrgobdote4f1r.mp4",
  LAUFEN_HUEFTDREHUNG_NACH_INNEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086785/claudia-clips/ipb3ntjlp4kq76hyhdzs.mp4",
  LAUFEN_RICHTUNGSWECHSEL:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086789/claudia-clips/dltmkt37cf5nle9zphcf.mp4",
  LAUFEN_SCHULTERKONTAKT:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086795/claudia-clips/stkbnxu05ehnewa6ognt.mp4",
  LAUFEN_SEITGALOPP:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086803/claudia-clips/puenzuauq3sqvwbey32d.mp4",
  LAUFEN_UEBER_DAS_SPIELFELD:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086806/claudia-clips/pfjonre13gmiuwemnhta.mp4",
  LAUFEN_VOR_UND_ZURUECK_SPRINTEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086812/claudia-clips/dwxfywklzjgokdcagxdd.mp4",
  OBERSCHENKELRUECKSEITE_LEVEL_1:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086815/claudia-clips/e2xdjieiefchenyze3j7.mp4",
  OBERSCHENKELRUECKSEITE_LEVEL_2:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086817/claudia-clips/ifvlxq86v3r7kwvxug54.mp4",
  OBERSCHENKELRUECKSEITE_LEVEL_3:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086822/claudia-clips/cf1wuizu9j7hcb2tkulq.mp4",
  SEITLICHER_UNTERARMSTUETZ_LEVEL_1_STATISCH_HALTEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086825/claudia-clips/n5qazf23sigd3zs9xsea.mp4",
  SEITLICHER_UNTERARMSTUETZ_LEVEL_2_HUEFTE_HEBEN_UND_SENKEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086828/claudia-clips/qifvsumi45i4ltzfmtpi.mp4",
  SEITLICHER_UNTERARMSTUETZ_LEVEL_3_MIT_BEINHEBEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086829/claudia-clips/vvz67kfh61qtaha7irjd.mp4",
  SPRINGEN_LEVEL_1_VERTIKALE_SPRUENGE:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086832/claudia-clips/e8i4nzveblb9jtld1zbs.mp4",
  SPRINGEN_LEVEL_2_SEITLICHE_SPRUENGE:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086837/claudia-clips/ugthdhfpgdjyg1a8rsb5.mp4",
  SPRINGEN_LEVEL_3_KASTENSPRUENGE:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086840/claudia-clips/qgwmnbyx0a2pksopdqwu.mp4",
  UNTERARMSTUETZ_LEVEL_1_STATISCH_HALTEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086842/claudia-clips/qgvxfvwaqgq12zfbi6yi.mp4",
  UNTERARMSTUETZ_LEVEL_2_BEINE_ABWECHSELND_ANHEBEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086844/claudia-clips/wpd668junkrnghbrzjs1.mp4",
  UNTERARMSTUETZ_LEVEL_3_EINBEINIGES_HALTEN:
    "https://res.cloudinary.com/dwedvwkzw/video/upload/v1759086847/claudia-clips/vzwq4veof2pvkmrautyg.mp4",
}
